training:
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 2 # Number of update steps to accumulate the gradients for
  per_device_eval_batch_size: 1
  eval_accumulation_steps: 1
  optim: paged_adamw_32bit
  save_steps: 5
  logging_steps: 5
  learning_rate: 2.e-4
  fp16: True
  #bf16: False # Set bf16 to True with an A100
  max_grad_norm: 0.3 # # Maximum gradient normal (gradient clipping)
  num_train_epochs: 1 # Number of training steps (overrides num_train_epochs)
  warmup_ratio: 0.03 # Ratio of steps for a linear warmup (from 0 to learning rate)
  lr_scheduler_type: constant
  evaluation_strategy: steps
  eval_steps: 5
  report_to: comet_ml
  seed: 42
  load_best_model_at_end: True
model:
  id: tiiuae/falcon-7b-instruct
  template: falcon
  max_seq_length: 1024
